# Generated by Django 2.0.3 on 2018-04-04 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='modification',
        ),
    ]
