# Generated by Django 2.0.3 on 2018-04-05 22:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180405_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Конпоненты'},
        ),
        migrations.AlterField(
            model_name='component',
            name='attributes',
            field=jsonfield.fields.JSONField(blank=True, default=dict, verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='component',
            name='template',
            field=models.CharField(max_length=100, verbose_name='Шаблон'),
        ),
    ]
