# Generated by Django 2.0.3 on 2018-04-05 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180405_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Основная'), ('1', 'Вложенная')], max_length=1, verbose_name='Тип')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Category', verbose_name='Родительская категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('old_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Старая цена')),
                ('discount', models.BooleanField(default=False, verbose_name='Пометка "акция"')),
                ('name', models.CharField(default='', max_length=512, verbose_name='Название')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Бренд')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='products/', verbose_name='Фотография')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.Category', verbose_name='Категория / подкатегория')),
            ],
        ),
    ]
