# Generated by Django 2.0.3 on 2018-04-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
