# Generated by Django 2.0.3 on 2018-04-17 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180408_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('status', models.CharField(choices=[('0', 'В обработке'), ('1', 'Подтвержден'), ('2', 'Доставлен'), ('3', 'Отменен')], default='0', max_length=1, verbose_name='Статус')),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(code='invalid_length_phone', message='Введите номер телефона в формате +7 (XXX) XXX-XX-XX', regex='\\+7 \\([0-9]{3}\\) [0-9]{3}-[0-9]{2}-[0-9]{2}')], verbose_name='Телефон')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_type', models.CharField(max_length=100, verbose_name='Способ доставки')),
                ('delivery_address', models.CharField(max_length=300, verbose_name='Адрес доставки')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Компонент', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='core.OrderItem', verbose_name='Элементы'),
        ),
    ]
