# Generated by Django 2.0.3 on 2018-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180417_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Сумма'), ('1', 'Проценты')], max_length=1, verbose_name='Тип')),
                ('value', models.PositiveIntegerField(verbose_name='Значение (сумма или %)')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('active', models.BooleanField(default=True, verbose_name='Активировать')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('free', models.PositiveIntegerField(verbose_name='Бесплатна при заказе от')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
