# Generated by Django 2.0.3 on 2018-04-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20180424_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Значение (руб или %)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Coupon', verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Delivery', verbose_name='Способ доставки'),
        ),
    ]
