# Generated by Django 2.0.3 on 2018-04-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180424_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_type',
        ),
    ]
