# Generated by Django 2.0.3 on 2018-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Производитель'),
        ),
    ]
