# Generated by Django 2.0.3 on 2018-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modifications',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.Modification', verbose_name='Модификации'),
        ),
    ]
