# Generated by Django 2.0.3 on 2018-06-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20180522_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='modifications',
        ),
        migrations.AddField(
            model_name='modification',
            name='main_product',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.Product', verbose_name='Главный товар'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_modifications', to='core.Product', verbose_name='Товар'),
        ),
    ]
