# Generated by Django 2.0.3 on 2018-06-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_property_propertyvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvariant',
            name='property',
        ),
        migrations.DeleteModel(
            name='PropertyVariant',
        ),
    ]
