# Generated by Django 2.0.3 on 2018-06-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20180611_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='main_product',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.Order', verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyhandler',
            name='filters',
            field=models.BooleanField(default=True, verbose_name='Использовать для фильтров'),
        ),
        migrations.AddField(
            model_name='propertyhandler',
            name='modifications',
            field=models.BooleanField(default=False, verbose_name='Использовать для модификаций'),
        ),
        migrations.DeleteModel(
            name='Modification',
        ),
    ]
