# Generated by Django 2.0.3 on 2018-06-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180611_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.Product', verbose_name='Корневой товар модификаций'),
        ),
    ]
